/*

 GROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : Z:\Users\guohai\Develop\gameboy-develop\my-gameboy-project\backgound.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GroundWidth 32
#define GroundHeight 18
#define GroundBank 0

extern unsigned char Ground[];

/* End of GROUND.H */
