/*

 GROUND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : Z:\Users\guohai\Developer\GameBoyProject\sample_codes\backgound.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GroundWidth 20
#define GroundHeight 1
#define GroundBank 0

unsigned char Ground[] =
{
  0x13,0x14,0x15,0x16,0x13,0x14,0x15,0x16,0x13,0x14,
  0x15,0x16,0x13,0x14,0x15,0x16,0x13,0x14,0x15,0x16
};

/* End of GROUND.C */
