/*

 REWARDCARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : Z:\Users\guohai\Developer\GameBoyProject\sample_codes\text.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define rcmapWidth 20
#define rcmapHeight 3
#define rcmapBank 0

extern unsigned char rcmap[];

/* End of REWARDCARD.H */
