/*

 WINDOWMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : Z:\Users\guohai\Develop\gameboy-develop\my-gameboy-project\boyandgirl.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define windowmapWidth 10
#define windowmapHeight 10
#define windowmapBank 0

unsigned char windowmap[] =
{
  0x04,0x05
};

/* End of WINDOWMAP.C */
